algo = input('Digite Algo:')
print(algo)
print(type(algo))
print(algo, 'São Letras ou Números? {} '.format(algo.isalnum()))
print(algo, 'Só tem Letras? {}'.format(algo.isalpha()))
print(algo, 'Só tem Números? {}'.format(algo.isnumeric()))
print(algo, 'Só tem Letras Maiúsculas? {}'.format(algo.isupper()))
print(algo, 'Só tem Letras Minúsculas? {}'.format(algo.islower()))
print(algo, 'Está capitalizado? {}'.format(algo.istitle()))
