nu = int(input('Digite um número: '))
print('{} X {:2} = {}'.format(nu, 1, nu * 1))
print('{} X {:2} = {}'.format(nu, 2, nu * 2))
print('{} X {:2} = {}'.format(nu, 3, nu * 3))
print('{} X {:2} = {}'.format(nu, 4, nu * 4))
print('{} X {:2} = {}'.format(nu, 5, nu * 5))
print('{} X {:2} = {}'.format(nu, 6, nu * 6))
print('{} X {:2} = {}'.format(nu, 7, nu * 8))
print('{} X {:2} = {}'.format(nu, 8, nu * 8))
print('{} X {:2} = {}'.format(nu, 9, nu * 9))
print('{} X {:2} = {}'.format(nu, 10, nu * 10))

